const jobs = [
  {
    brandLogo: "https://logo.clearbit.com/meta.com",
    company: "Meta",
    date: "5 days ago",
    post: "Frontend Developer",
    tag1: "Full Time",
    tag2: "Senior Level",
    pay: "$85/hr",
    location: "Menlo Park, USA",
  },
  {
    brandLogo: "https://logo.clearbit.com/apple.com",
    company: "Apple",
    date: "1 week ago",
    post: "UI/UX Designer",
    tag1: "Full Time",
    tag2: "Mid Level",
    pay: "$70/hr",
    location: "Cupertino, USA",
  },
  {
    brandLogo: "https://logo.clearbit.com/amazon.com",
    company: "Amazon",
    date: "3 weeks ago",
    post: "Backend Developer",
    tag1: "Part Time",
    tag2: "Junior Level",
    pay: "$60/hr",
    location: "Bangalore, India",
  },
  {
    brandLogo: "https://logo.clearbit.com/netflix.com",
    company: "Netflix",
    date: "2 days ago",
    post: "Product Designer",
    tag1: "Full Time",
    tag2: "Senior Level",
    pay: "$90/hr",
    location: "Los Gatos, USA",
  },
  {
    brandLogo: "https://logo.clearbit.com/google.com",
    company: "Google",
    date: "10 weeks ago",
    post: "Software Engineer",
    tag1: "Full Time",
    tag2: "Junior Level",
    pay: "$75/hr",
    location: "Hyderabad, India",
  },
  {
    brandLogo: "https://logo.clearbit.com/microsoft.com",
    company: "Microsoft",
    date: "4 days ago",
    post: "Cloud Architect",
    tag1: "Full Time",
    tag2: "Senior Level",
    pay: "$95/hr",
    location: "Redmond, USA",
  },
  {
    brandLogo: "https://logo.clearbit.com/tesla.com",
    company: "Tesla",
    date: "2 weeks ago",
    post: "Data Scientist",
    tag1: "Part Time",
    tag2: "Mid Level",
    pay: "$80/hr",
    location: "Austin, USA",
  },
  {
    brandLogo: "https://logo.clearbit.com/spotify.com",
    company: "Spotify",
    date: "1 month ago",
    post: "React Developer",
    tag1: "Full Time",
    tag2: "Junior Level",
    pay: "$65/hr",
    location: "Stockholm, Sweden",
  },
  {
    brandLogo: "https://logo.clearbit.com/adobe.com",
    company: "Adobe",
    date: "6 days ago",
    post: "Graphic Designer",
    tag1: "Full Time",
    tag2: "Mid Level",
    pay: "$55/hr",
    location: "San Jose, USA",
  },
  {
    brandLogo: "https://logo.clearbit.com/nvidia.com",
    company: "Nvidia",
    date: "3 weeks ago",
    post: "AI Research Engineer",
    tag1: "Full Time",
    tag2: "Senior Level",
    pay: "$120/hr",
    location: "Santa Clara, USA",
  },
];

export default jobs;
